[package]
name = "spin"
version = "0.1.0"
edition = "2021"
authors = [ "Fermyon Engineering <engineering@fermyon.com>" ]

[dependencies]
anyhow = "1.0"
async-trait = "0.1"
bindle = { version = "0.8.0", default-features = false, features = ["client"] }
bytes = "1.1"
comfy-table = "5.0"
dirs = "4.0"
dunce = "1.0"
env_logger = "0.9"
futures = "0.3"
lazy_static = "1.4.0"
path-absolutize = "3.0.11"
semver = "1.0"
serde = { version = "1.0", features = [ "derive" ] }
spin-config = { path = "crates/config" }
spin-engine = { path = "crates/engine" }
spin-http-engine = { path = "crates/http" }
spin-loader = { path = "crates/loader" }
spin-manifest = { path = "crates/manifest" }
spin-publish = { path = "crates/publish" }
spin-redis-engine = { path = "crates/redis" }
spin-templates = { path = "crates/templates" }
structopt = "0.3"
tempfile = "3.3.0"
tokio = { version = "1.11", features = [ "full" ] }
toml = "0.5"
tracing = { version = "0.1", features = [ "log" ] }
tracing-futures = "0.2"
tracing-subscriber = { version = "0.3.7", features = [ "env-filter" ] }

[dev-dependencies]
hyper = { version = "0.14", features = [ "full" ] }

[build-dependencies]
cargo-target-dep = { git = "https://github.com/fermyon/cargo-target-dep", rev = "b7b1989fe0984c0f7c4966398304c6538e52fe49" }
vergen = { version = "7", default-features = false, features = [ "build", "git" ] }

[workspace]
members = [
    "crates/config",
    "crates/engine",
    "crates/http",
    "crates/loader",
    "crates/manifest",
    "crates/object-store",
    "crates/outbound-http",
    "crates/redis",
    "crates/templates",
    "crates/testing",
    "examples/spin-timer",
    "sdk/rust",
    "sdk/rust/macro"
]

# [[bin]]
# name = "spin"
# path = "src/bin/spin.rs"

[lib]
name = "spin"
crate-type = ["staticlib"]
path = "src/lib.rs"
