default interface worker {
  type payload = list<u8>

  variant exec-error {
//    nonexistent-component,
//    io(string),
//    other(string),
    ohno,
  }

  exec: func(id: string, payload: payload) -> result<_, exec-error>
}
